---
title: "Основы геоинформатики"
subtitle: "Лекция 2: Основные понятия"
date: 10.02.2023
author: "Самсонов Тимофей Евгеньевич"
execute:
  echo: false
engine: knitr
format:
  revealjs: 
    theme: [default, custom.scss]
    slide-number: true
bibliography: references.yaml
---

## Пространственная привязка

**Пространственная привязка [@gost:70316-2022]**

:   Описание позиции в реальном мире.

Пространственная привязка может быть осуществлена двумя основными способами:

-   с использованием координат;
-   **посредством географических идентификаторов**.

::: callout-important
## Система координат

При использовании привязки по координатам необходимо описание системы координат.
:::

## Географические идентификаторы

Увязаны с местоположением, идентифицируемым географическими объектами. Взаимосвязь с объектом может быть установлена следующими основными способами:

-   **локализацией**, когда конкретная позиция находится внутри географического объекта, например в стране;

-   **локальными измерениями**, когда позиция определена относительно фиксированных точек географических объектов, например вдоль улицы на заданном расстоянии от пересечения с другой улицей. Этот аспект известен как *линейная привязка*;

-   **слабо связанным способом**, когда позиция имеет нечеткую взаимосвязь с географическими объектами, например рядом со зданием или между двумя зданиями.
